#!/bin/bash

chrome_flatpak_dir=`flatpak-spawn --host flatpak info -l com.google.Chrome`
chrome_binary=${chrome_flatpak_dir}/files/extra/opt/google/chrome/google-chrome

exec flatpak-spawn --host ${chrome_binary} $@
